version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - nextjs-network
    ports:
      - "3000:3000"
      - "3001:3001"

  # Optional: Add database service (uncomment if needed)
  # postgres:
  #   image: postgres:15
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: nextjs_db
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - nextjs-network
  #   ports:
  #     - "5432:5432"

  # Optional: Add Redis cache (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   networks:
  #     - nextjs-network
  #   ports:
  #     - "6379:6379"

networks:
  nextjs-network:
    driver: bridge

# volumes:
#   postgres-data: